version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      day: "thursday"
      time: "01:00"
      timezone: "America/Los_Angeles"
    labels:
      - "dependencies"
      - "github-actions"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      day: "thursday"
      time: "01:00"
      timezone: "America/Los_Angeles"
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
        update-types:
          - "major"
          - "minor"
          - "patch"
      tiptap-editor:
        patterns:
          - "@tiptap/*"
          - "tiptap-*"
        update-types:
          - "major"
          - "minor"
          - "patch"
    labels:
      - "dependencies"
      - "npm"
    open-pull-requests-limit: 5

  - package-ecosystem: "cargo"
    directory: "/src-tauri"
    schedule:
      interval: "daily"
      day: "thursday"
      time: "01:00"
      timezone: "America/Los_Angeles"
    labels:
      - "dependencies"
      - "rust"
    open-pull-requests-limit: 5
